version: "3"
services:
  syno-debian-test:
#    image: gpopesc/xfce-debian-synology
    container_name: syno-debian-test
    build: .
    environment:
      - VNCPASS=$VNC               
      - DISPLAY_WIDTH=$WIDTH
      - DISPLAY_HEIGHT=$HEIGHT
      - TZ=$TZ
      - UID=$UID
      - GID=$GID
      - USER_NAME=$USER_NAME      
      - USER_PASSWORD=$USER_PASS  
    ports:
      - $VNCPORT:5900   
      - $HTTPPORT:8000
    volumes:
      - ./data:/home/$USER_NAME
#      - $LOCAL_PATH:/home/$USER_NAME/share                  # uncomment if want to mount additional share
      - /run/user/$UID/pulse:/run/user/$UID/pulse:ro        # uncomment in linux if you want sound
      - type: tmpfs
        target: /dev/shm
        tmpfs:
         size: 4000000000 # ~4gb
    restart: on-failure
