version: "3"
services:
  evi-rent:
    image: gpopesc/evi-rent
    container_name: evi-rent
    environment:
      - VNCPASS=admin
      - DISPLAY_WIDTH=1200
      - DISPLAY_HEIGHT=720
      - TZ=Europe/Bucharest
    ports:
      - 5910:5900   #vnc port
      - 8787:8080   #http port
    volumes:
#      - ./data:/root/Downloads
      - ./data/root:/root #map root if you want to save all your seetings 
      - /volume1/web/afterlogicpro/data/files/private/c2034715-a07f-46a8-afa3-8a978739789d:/root/share
      - type: tmpfs
        target: /dev/shm
        tmpfs:
         size: 4000000000 # ~4gb
    restart: unless-stopped
